# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0719461f8adc0b507ce573743e18931b29cfca142308ffd5c3c0d19094678ece3ce2782d5dc099868d818e5ae495c76ae71d28eededa9a6f2fcdc7031c30b52

test:
  secret_key_base: e3c1bc532e49275335fc6294260caaa1e27d9bce4690e4b3cdd59cea33f18ed1240de2a0222c164416111531d0744937ad1392cfa5b19dd9ac1eb2ef2f02ca01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
